### ISSUE TITLE
Support for default ttl in case of absent tag

### ISSUE THREAD

**Issue by whiskeysierra** [webdevops/azure-janitor#1]
We're having a dedicated *playground* subscription which engineers can use to prototype with Azure resources.
It would be nice to have a default ttl which applies to all resource groups without a ttl tag.

I realize that this is a very dangerous feature, if it's not used properly.
But for cases like this, it seems really powerful.

**Comment by mblaschke** [comment]
could an azure policy solve this issue? just add a ttl tag to all RGs and resources with eg `31d`

**Comment by mblaschke** [comment]
Feedback?
